[project]
name = "3000"
version = "0.1"
dependencies = [
  "notebook",
  "jupyterlab"
]
readme = "README.md"
requires-python = ">=3.9"

[project.optional-dependencies]
dev = ["black[jupyter]", "pytest"]
